### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by lucav17** [sjbcodes/f1-3-c2p1-colmar-academy#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_  Great job! You imported your CSS file correctly and referenced HTML attributes from it well!
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_  4
* _Comment(s):_  Overall the site looked perfect. This showed a great understanding of HTML and CSS!
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_ Great job spacing out your code and assigning comments!
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_  4
* _Comment(s):_  Overall the CSS file was well put together. You showed great skill in creating efficient CSS
 
### Overall Score: 16/16
Well done!

**Comment by sjbcodes** [comment]
Thanks Luca!
